/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前匿名用户的历史对话 */
        get: operations["listConversations"];
        put?: never;
        /**
         * 用第一条用户消息创建对话
         * @description 不创建空对话。若没有匿名会话 Cookie，服务端创建会话并通过 HttpOnly Cookie 返回。
         *     相同 Idempotency-Key 和 client_message_id 的安全重试必须返回第一次结果。
         */
        post: operations["createConversation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 恢复对话页面所需的聚合快照 */
        get: operations["getConversation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 向前分页加载更早消息 */
        get: operations["listConversationMessages"];
        put?: never;
        /** 回答追问或基于当前行程提出修改 */
        post: operations["createConversationMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询首次生成或修改任务的真实状态
         * @description Run 已接受后的上游失败通过 status=failed 和 error 表达，本接口仍返回 200。
         */
        get: operations["getRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取指定的不可变行程版本 */
        get: operations["getPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/photo-spots/featured": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取首页北京出片灵感 */
        get: operations["listFeaturedPhotoSpots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查 */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 不透明字符串 ID；消费者不得依赖前缀或把它转为数字。 */
        OpaqueId: string;
        NullableOpaqueId: components["schemas"]["OpaqueId"] | null;
        CreateConversationRequest: {
            client_message_id: components["schemas"]["OpaqueId"];
            text: string;
        };
        CreateMessageRequest: {
            client_message_id: components["schemas"]["OpaqueId"];
            text: string;
            reply_to_message_id: components["schemas"]["NullableOpaqueId"];
            structured_answer: components["schemas"]["StructuredAnswer"] | null;
            base_plan_id: components["schemas"]["NullableOpaqueId"];
        };
        StructuredAnswer: components["schemas"]["DaysAnswer"] | components["schemas"]["StartDateAnswer"] | components["schemas"]["PaceAnswer"];
        DaysAnswer: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            slot: "days";
            /** @enum {integer} */
            value: 1 | 2 | 3 | 4 | 5;
        };
        StartDateAnswer: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            slot: "start_date";
            value: string | "pending";
        };
        PaceAnswer: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            slot: "pace";
            /** @enum {string} */
            value: "轻松" | "适中" | "紧凑";
        };
        /** @enum {string} */
        ConversationStatus: "collecting_requirements" | "generating" | "completed" | "failed" | "archived";
        RequirementsSnapshot: {
            /** @constant */
            city: "北京";
            days: number | null;
            /** @enum {string} */
            date_status: "unknown" | "specified" | "pending";
            /** Format: date */
            start_date: string | null;
            party_size: number | null;
            companion_types: string[];
            must_include: string[];
            must_exclude: string[];
            interests: string[];
            photo_preferences: string[];
            /** @enum {string|null} */
            pace: "轻松" | "适中" | "紧凑" | null;
            lodging_text: string | null;
            transport_preferences: string[];
            missing_slots: ("days" | "start_date" | "pace")[];
        } & (unknown & unknown);
        Conversation: {
            id: components["schemas"]["OpaqueId"];
            title: string;
            status: components["schemas"]["ConversationStatus"];
            requirements: components["schemas"]["RequirementsSnapshot"];
            latest_plan_id: components["schemas"]["NullableOpaqueId"];
            active_run_id: components["schemas"]["NullableOpaqueId"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        } & (unknown & unknown & unknown);
        ConversationSummary: {
            id: components["schemas"]["OpaqueId"];
            title: string;
            preview: string;
            status: components["schemas"]["ConversationStatus"];
            latest_plan_id: components["schemas"]["NullableOpaqueId"];
            /** Format: date-time */
            updated_at: string;
        };
        /** @enum {string} */
        MessageRole: "user" | "assistant" | "system";
        /** @enum {string} */
        MessageContentType: "text" | "clarification" | "run_started" | "plan_created" | "plan_updated" | "error";
        ClarificationOption: {
            label: string;
            value: number | string;
        };
        ClarificationContent: {
            /** @constant */
            kind: "clarification";
            /** @enum {string} */
            slot: "days" | "start_date" | "pace";
            /** @enum {string} */
            control: "single_select" | "date_or_pending";
            options: components["schemas"]["ClarificationOption"][];
            allow_pending: boolean;
        };
        RunStartedContent: {
            /** @constant */
            kind: "run_started";
            run_id: components["schemas"]["OpaqueId"];
        };
        PlanEventContent: {
            /** @enum {string} */
            kind: "plan_created" | "plan_updated";
            plan_id: components["schemas"]["OpaqueId"];
            version: number;
            changed_days: number[];
            change_summary: string[];
        };
        ErrorMessageContent: {
            /** @constant */
            kind: "error";
            code: string;
            recoverable: boolean;
        };
        MessageStructuredContent: components["schemas"]["ClarificationContent"] | components["schemas"]["RunStartedContent"] | components["schemas"]["PlanEventContent"] | components["schemas"]["ErrorMessageContent"];
        Message: {
            id: components["schemas"]["OpaqueId"];
            conversation_id: components["schemas"]["OpaqueId"];
            role: components["schemas"]["MessageRole"];
            content_type: components["schemas"]["MessageContentType"];
            text: string;
            structured_content: components["schemas"]["MessageStructuredContent"] | null;
            reply_to_message_id: components["schemas"]["NullableOpaqueId"];
            run_id: components["schemas"]["NullableOpaqueId"];
            plan_id: components["schemas"]["NullableOpaqueId"];
            /** Format: date-time */
            created_at: string;
        } & (unknown & unknown & unknown & unknown & unknown);
        /** @enum {string} */
        RunKind: "initial_plan" | "revision";
        /** @enum {string} */
        RunStatus: "queued" | "running" | "succeeded" | "failed";
        /** @enum {string} */
        RunStageStatus: "waiting" | "running" | "succeeded" | "failed" | "skipped";
        RunStage: {
            /** @enum {string} */
            key: "understanding_request" | "resolving_pois" | "planning_routes" | "recommending_lodging" | "retrieving_photo_spots" | "validating";
            label: string;
            status: components["schemas"]["RunStageStatus"];
            /** Format: date-time */
            started_at: string | null;
            /** Format: date-time */
            completed_at: string | null;
        };
        RunError: {
            code: string;
            message: string;
            recoverable: boolean;
        };
        Run: {
            id: components["schemas"]["OpaqueId"];
            conversation_id: components["schemas"]["OpaqueId"];
            kind: components["schemas"]["RunKind"];
            status: components["schemas"]["RunStatus"];
            trigger_message_id: components["schemas"]["OpaqueId"];
            base_plan_id: components["schemas"]["NullableOpaqueId"];
            result_plan_id: components["schemas"]["NullableOpaqueId"];
            /** @enum {string|null} */
            current_stage: "understanding_request" | "resolving_pois" | "planning_routes" | "recommending_lodging" | "retrieving_photo_spots" | "validating" | null;
            stages: components["schemas"]["RunStage"][];
            error: components["schemas"]["RunError"] | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            started_at: string | null;
            /** Format: date-time */
            finished_at: string | null;
        } & (unknown & unknown & unknown & unknown);
        Coordinate: {
            latitude: number;
            longitude: number;
            /** @enum {string} */
            coordinate_system: "GCJ-02" | "WGS-84" | "BD-09";
        };
        POI: {
            poi_id: components["schemas"]["OpaqueId"];
            canonical_name: string;
            map_source: string | null;
        };
        RouteSegment: {
            origin_poi_id: components["schemas"]["OpaqueId"];
            destination_poi_id: components["schemas"]["OpaqueId"];
            /** @enum {string} */
            recommended_mode: "步行" | "公共交通" | "打车" | "驾车";
            duration_min: number;
            distance_km: number;
            cost_cny: number | null;
            walk_distance_m: number | null;
            transfers: number | null;
            reason: string;
        };
        ReferencePhoto: {
            image_id: components["schemas"]["OpaqueId"];
            /** Format: uri */
            storage_url: string;
            /** Format: uri */
            thumbnail_url: string | null;
            source_id: components["schemas"]["OpaqueId"];
        };
        SourceRef: {
            source_id: components["schemas"]["OpaqueId"];
            source_platform: string;
            source_author: string | null;
            /** Format: uri */
            source_url: string;
            evidence_ids: components["schemas"]["OpaqueId"][];
        };
        BestTime: {
            /** @enum {string} */
            type: "固定时段" | "日出关联" | "日落关联" | "亮灯后" | "季节性";
            display_text: string;
            applicable_seasons: string[] | null;
            applicable_weather: string[] | null;
            source_ids: components["schemas"]["OpaqueId"][];
            confidence: number;
        };
        PhotoSpotHit: {
            spot_id: components["schemas"]["OpaqueId"];
            poi_id: components["schemas"]["OpaqueId"];
            spot_name: string;
            coordinate: components["schemas"]["Coordinate"];
            location_description: string;
            positioning_guide: string | null;
            /** @enum {string} */
            location_precision: "exact_poi" | "named_sub_poi" | "approximate";
            reference_photos: components["schemas"]["ReferencePhoto"][];
            best_time: components["schemas"]["BestTime"] | null;
            source_refs: components["schemas"]["SourceRef"][];
            /** @constant */
            ingestion_status: "auto_verified";
            confidence: number;
        };
        ItineraryItem: {
            item_id: components["schemas"]["OpaqueId"];
            poi: components["schemas"]["POI"];
            start_time: string | null;
            end_time: string | null;
            stay_duration_min: number;
            booking_reminder: string | null;
            entry_tip: string | null;
            route_from_previous: components["schemas"]["RouteSegment"] | null;
            photo_spots: components["schemas"]["PhotoSpotHit"][];
        };
        DayOrigin: {
            /** @enum {string} */
            type: "user_lodging" | "recommended_area";
            poi_id: components["schemas"]["OpaqueId"];
            name: string;
        };
        ItineraryDaySummary: {
            estimated_duration_min: number;
            dominant_transport_modes: ("步行" | "公共交通" | "打车" | "驾车")[];
            estimated_walk_distance_m: number | null;
        };
        ItineraryDay: {
            day_index: number;
            /** Format: date */
            date: string | null;
            theme: string | null;
            start_time: string | null;
            end_time: string | null;
            origin: components["schemas"]["DayOrigin"];
            outbound_route: components["schemas"]["RouteSegment"] | null;
            items: components["schemas"]["ItineraryItem"][];
            return_route: components["schemas"]["RouteSegment"] | null;
            summary: components["schemas"]["ItineraryDaySummary"];
        };
        LodgingRecommendation: {
            area_id: components["schemas"]["OpaqueId"];
            name: string;
            /** @enum {string} */
            level: "首选" | "备选" | "当前住宿评估";
            representative_station: string | null;
            reason: string;
            covered_attractions: string[];
            avg_transit_min: number | null;
        };
        Limitation: {
            code: string;
            message: string;
        };
        ValidationCheck: {
            code: string;
            /** @enum {string} */
            severity: "fail" | "warning" | "spot_fail";
            message: string;
            day_index: number | null;
            item_id: components["schemas"]["NullableOpaqueId"];
            spot_id: components["schemas"]["NullableOpaqueId"];
        };
        ValidationResult: {
            /** @enum {string} */
            status: "pass" | "fail";
            checks: components["schemas"]["ValidationCheck"][];
            /** Format: date-time */
            checked_at: string;
        };
        PlannerInfo: {
            model: string | null;
            model_version: string | null;
            prompt_version: string;
        };
        ItineraryPlan: {
            /** @constant */
            schema_version: "1.2.0";
            plan_id: components["schemas"]["OpaqueId"];
            request_id: components["schemas"]["OpaqueId"];
            /** @constant */
            status: "validated";
            title: string;
            overview: string;
            request_summary: {
                [key: string]: unknown;
            };
            lodging_recommendations: components["schemas"]["LodgingRecommendation"][];
            days: components["schemas"]["ItineraryDay"][];
            limitations: components["schemas"]["Limitation"][];
            validation: components["schemas"]["ValidationResult"];
            planner: components["schemas"]["PlannerInfo"];
            /** Format: date-time */
            generated_at: string;
        };
        PlanVersion: {
            id: components["schemas"]["OpaqueId"];
            conversation_id: components["schemas"]["OpaqueId"];
            run_id: components["schemas"]["OpaqueId"];
            version: number;
            base_plan_id: components["schemas"]["NullableOpaqueId"];
            /** @constant */
            status: "validated";
            changed_days: number[];
            change_summary: string[];
            plan: components["schemas"]["ItineraryPlan"];
            retrieval_run_ids: components["schemas"]["OpaqueId"][];
            knowledge_index_version: string;
            /** Format: date-time */
            created_at: string;
        };
        ConversationTurnData: {
            conversation: components["schemas"]["Conversation"];
            accepted_message: components["schemas"]["Message"];
            assistant_messages: components["schemas"]["Message"][];
            active_run: components["schemas"]["Run"] | null;
            latest_plan: components["schemas"]["PlanVersion"] | null;
        };
        ConversationTurnResponse: {
            data: components["schemas"]["ConversationTurnData"];
        };
        ConversationSnapshotData: {
            conversation: components["schemas"]["Conversation"];
            messages: components["schemas"]["Message"][];
            message_page: components["schemas"]["BackwardPageMeta"];
            active_run: components["schemas"]["Run"] | null;
            latest_plan: components["schemas"]["PlanVersion"] | null;
        };
        ConversationSnapshotResponse: {
            data: components["schemas"]["ConversationSnapshotData"];
        };
        ForwardPageMeta: {
            has_next: boolean;
            next_cursor: string | null;
        };
        BackwardPageMeta: {
            has_more: boolean;
            before_cursor: string | null;
        };
        ConversationListResponse: {
            data: components["schemas"]["ConversationSummary"][];
            meta: components["schemas"]["ForwardPageMeta"];
        };
        MessageListResponse: {
            data: components["schemas"]["Message"][];
            meta: components["schemas"]["BackwardPageMeta"];
        };
        RunResponse: {
            data: components["schemas"]["Run"];
        };
        PlanVersionResponse: {
            data: components["schemas"]["PlanVersion"];
        };
        FeaturedPhotoSpot: {
            spot_id: components["schemas"]["OpaqueId"];
            poi_id: components["schemas"]["OpaqueId"];
            poi_name: string;
            spot_name: string;
            cover_image: components["schemas"]["ReferencePhoto"] | null;
            location_description: string;
            best_time: components["schemas"]["BestTime"] | null;
            source: components["schemas"]["SourceRef"] | null;
        };
        FeaturedPhotoSpotListResponse: {
            data: components["schemas"]["FeaturedPhotoSpot"][];
        };
        HealthResponse: {
            data: {
                /** @constant */
                status: "ok";
            };
        };
        ErrorDetail: {
            field: string | null;
            code: string;
            message: string;
        };
        ApiError: {
            code: string;
            message: string;
            details: components["schemas"]["ErrorDetail"][];
            request_id: components["schemas"]["OpaqueId"];
        };
        ApiErrorResponse: {
            error: components["schemas"]["ApiError"];
        };
    };
    responses: {
        /** @description JSON 格式错误或缺少必要请求信息 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiErrorResponse"];
            };
        };
        /** @description 缺少或无法验证匿名会话 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiErrorResponse"];
            };
        };
        /** @description 资源不存在或不属于当前匿名用户 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiErrorResponse"];
            };
        };
        /** @description 正在运行、版本过期、重复回答或幂等冲突 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiErrorResponse"];
            };
        };
        /** @description 请求可解析但字段或业务语义无效 */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiErrorResponse"];
            };
        };
        /** @description 请求频率超过限制 */
        RateLimited: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiErrorResponse"];
            };
        };
        /** @description 在形成可轮询 Run 之前发生的同步模型、地图或 RAG 上游失败 */
        UpstreamFailure: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiErrorResponse"];
            };
        };
        /** @description 服务暂时不可用 */
        ServiceUnavailable: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiErrorResponse"];
            };
        };
        /** @description 未预期错误，不返回内部堆栈 */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiErrorResponse"];
            };
        };
    };
    parameters: {
        ConversationId: components["schemas"]["OpaqueId"];
        RunId: components["schemas"]["OpaqueId"];
        PlanId: components["schemas"]["OpaqueId"];
        /** @description 网络重试时必须复用同一个 UUID */
        IdempotencyKey: string;
        Cursor: string | null;
        BeforeCursor: string | null;
        ConversationLimit: number;
        MessageLimit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listConversations: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["ConversationLimit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 按 updated_at 和 id 倒序返回的历史对话 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    createConversation: {
        parameters: {
            query?: never;
            header: {
                /** @description 网络重试时必须复用同一个 UUID */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationRequest"];
            };
        };
        responses: {
            /** @description 对话和首轮消息已创建 */
            201: {
                headers: {
                    /** @description 新 Conversation 的 API 地址 */
                    Location?: string;
                    /** @description 没有匿名会话时设置 HttpOnly trip_session Cookie */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationTurnResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["UpstreamFailure"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 最新 50 条消息、active Run 和最新有效 Plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSnapshotResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listConversationMessages: {
        parameters: {
            query?: {
                before?: components["parameters"]["BeforeCursor"];
                limit?: components["parameters"]["MessageLimit"];
            };
            header?: never;
            path: {
                conversation_id: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 按时间正序返回的一页消息 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    createConversationMessage: {
        parameters: {
            query?: never;
            header: {
                /** @description 网络重试时必须复用同一个 UUID */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                conversation_id: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMessageRequest"];
            };
        };
        responses: {
            /** @description 用户消息已保存，并返回本轮 assistant 消息及可能创建的 Run */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationTurnResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
            502: components["responses"]["UpstreamFailure"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: components["parameters"]["RunId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run 当前状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    getPlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: components["parameters"]["PlanId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 指定 PlanVersion */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanVersionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listFeaturedPhotoSpots: {
        parameters: {
            query?: {
                city?: "北京";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 只包含已准入、来源完整的精选机位 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeaturedPhotoSpotListResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务正常 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
